steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --source=./
      - --runtime=python38
      - --entry-point=main
      - --trigger-topic=${_TRIGGER_PUBSUB_TOPIC}
      - --timeout=540
      - --memory=512MB
      - --env-vars-file=.env.yaml
substitutions:
  _FUNCTION_NAME: crawl_livechat
  _REGION: asia-northeast1
  _SERVICE_ACCOUNT: ""
  _TRIGGER_PUBSUB_TOPIC: youtube-livechat-crawler
