steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --region=${_REGION}
      - --service-account=${_SERVICE_ACCOUNT}
      - --source=./
      - --runtime=python38
      - --entry-point=main
      - --trigger-bucket=${_TRIGGER_GCS_BUCKET}
      - --timeout=180
      - --env-vars-file=.env.yaml
substitutions:
  _FUNCTION_NAME: convert_bigquery_data
  _REGION: asia-northeast1
  _SERVICE_ACCOUNT: ""
  _TRIGGER_GCS_BUCKET: youtube-livechat-crawler
